version: "3"

volumes:
  postgres_data: {}
services:
  postgres:
    image: postgres:10.4
    restart: always
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "35432:5432"
    environment:
      NODE_ENV: development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
      DATABASE_URL: postgres://user:pass@postgres:5432/db


  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres